use_frameworks!

platform :ios, '10.0'

target 'HHUtils_Example' do
  pod 'HHUtils', :path => '../'

  target 'HHUtils_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      #      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      #      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
